Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 1
  end

  config.berkshelf.enabled = true

  config.vm.provision :chef_solo do |chef|
    chef.run_list = [
      "recipe[salt_edge::ruby]",
      "recipe[salt_edge::mongo]",
      "recipe[salt_edge::errbit]",
      "recipe[salt_edge::tests]"
    ]
    chef.arguments = "--chef-license accept"
  end
end
